# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jyotiprakashh
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: spotify-api
service: spotify-api

provider:
  name: aws
  region: us-east-1
  deploymentMethod: direct
  environment:
    SPOTIFY_ID: ${env:SPOTIFY_ID}
    SPOTIFY_SECRET: ${env:SPOTIFY_SECRET}
    SPOTIFY_REDIRECT_URI: ${env:SPOTIFY_REDIRECT_URI}

functions:
  generatePlaylist:
    handler: bin/generate_playlist
    events:
      - http:
          path: generate-playlist
          method: post
          cors: true
  addPlaylist:
    handler: bin/add_playlist
    events:
      - http:
          path: add-playlist
          method: post
          cors: true
  userProfile:
    handler: bin/user_profile
    events:
      - http:
          path: user-profile
          method: get
          cors: true
  login:
    handler: bin/login
    events:
      - http:
          path: login
          method: get
          cors: true
  callback:
    handler: bin/callback
    events:
      - http:
          path: callback
          method: get
          cors: true
  logout:
    handler: bin/logout
    events:
      - http:
          path: logout
          method: get
          cors: true
